services:
  - type: web
    name: bidxpert
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py loaddata initial_data.json
    startCommand: gunicorn BidXpert_pro.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: BidXpert_pro.settings
